export default (sequelize, DataTypes) => {

  const PresetPermissions = sequelize.define('PresetPermissions', {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },

    role: {
      type: DataTypes.ENUM('SUPER-ADMIN', 'ADMIN', 'MOD', 'POLICE', 'STREAMER', 'USER', 'VIP'),
      allowNull: false
    },

    permissionKey: {
      type: DataTypes.STRING,
      allowNull: false
    },

    active: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: true
    }
  }, {
    tableName: 'preset_permissions',
    timestamps: true,
    indexes: [
      {
        name: 'preset_permissions_role_permission_unique',
        unique: true,
        fields: ['role', 'permissionKey']
      },
      {
        name: 'preset_permissions_role_index',
        fields: ['role']
      }
    ]
  });

  PresetPermissions.seed = async () => {
    const seedPresetPermissions = [
      { role: 'SUPER-ADMIN', permissionKey: 'menu.start', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.tickets', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.users', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.userscontrol', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.reports', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.profile', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.configuration', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.players', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.news', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news.create', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news.delete', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.download', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.aboutapp', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.community', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'community.manage', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'menu.gestion', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.roles', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.permissions', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.statuses', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.editions', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.tickets', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.news', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'Commands.manage', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'Communities.admin', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'gest.system', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'tickets.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'tickets.manage', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'tickets.close', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'user.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'user.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'users.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'users.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'commands.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'commands.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'commands.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'communities.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'communities.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'communities.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'devices.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'devices.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'editions.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'editions.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'editions.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'editions.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news_types.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news_types.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news_types.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'news_types.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'permissions.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'permissions.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'permissions.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'permissions.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'roles.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'roles.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'roles.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'roles.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'sessions.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'sessions.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'statuses.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'statuses.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'statuses.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'statuses.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'system.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'system.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'system.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_catalogs.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_catalogs.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_catalogs.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_catalogs.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_statuses.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_statuses.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_statuses.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'ticket_statuses.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'emblems.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'emblems.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'emblems.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'emblems.give', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'emblems.remove', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'goals.view', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'goals.gest', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'goals.edit', active: true },
      { role: 'SUPER-ADMIN', permissionKey: 'goals.remove', active: true },

      { role: 'ADMIN', permissionKey: 'menu.start', active: true },
      { role: 'ADMIN', permissionKey: 'menu.tickets', active: true },
      { role: 'ADMIN', permissionKey: 'menu.users', active: true },
      { role: 'ADMIN', permissionKey: 'menu.userscontrol', active: true },
      { role: 'ADMIN', permissionKey: 'menu.reports', active: true },
      { role: 'ADMIN', permissionKey: 'menu.profile', active: true },
      { role: 'ADMIN', permissionKey: 'menu.configuration', active: true },
      { role: 'ADMIN', permissionKey: 'menu.players', active: true },
      { role: 'ADMIN', permissionKey: 'menu.news', active: true },
      { role: 'ADMIN', permissionKey: 'news.create', active: true },
      { role: 'ADMIN', permissionKey: 'news.edit', active: true },
      { role: 'ADMIN', permissionKey: 'news.delete', active: true },
      { role: 'ADMIN', permissionKey: 'menu.download', active: true },
      { role: 'ADMIN', permissionKey: 'menu.aboutapp', active: true },
      { role: 'ADMIN', permissionKey: 'menu.community', active: true },
      { role: 'ADMIN', permissionKey: 'menu.gestion', active: true },
      { role: 'ADMIN', permissionKey: 'gest.roles', active: true },
      { role: 'ADMIN', permissionKey: 'gest.permissions', active: true },
      { role: 'ADMIN', permissionKey: 'gest.statuses', active: true },
      { role: 'ADMIN', permissionKey: 'gest.editions', active: true },
      { role: 'ADMIN', permissionKey: 'gest.tickets', active: true },
      { role: 'ADMIN', permissionKey: 'gest.news', active: true },
      { role: 'ADMIN', permissionKey: 'Commands.manage', active: true },
      { role: 'ADMIN', permissionKey: 'Communities.admin', active: true },
      { role: 'ADMIN', permissionKey: 'gest.system', active: true },
      { role: 'ADMIN', permissionKey: 'tickets.view', active: true },
      { role: 'ADMIN', permissionKey: 'tickets.manage', active: true },
      { role: 'ADMIN', permissionKey: 'tickets.close', active: true },
      { role: 'ADMIN', permissionKey: 'user.view', active: true },
      { role: 'ADMIN', permissionKey: 'user.edit', active: true },
      { role: 'ADMIN', permissionKey: 'users.view', active: true },
      { role: 'ADMIN', permissionKey: 'users.edit', active: true },
      { role: 'ADMIN', permissionKey: 'commands.view', active: true },
      { role: 'ADMIN', permissionKey: 'commands.gest', active: true },
      { role: 'ADMIN', permissionKey: 'commands.edit', active: true },
      { role: 'ADMIN', permissionKey: 'communities.view', active: true },
      { role: 'ADMIN', permissionKey: 'communities.gest', active: true },
      { role: 'ADMIN', permissionKey: 'communities.remove', active: true },
      { role: 'ADMIN', permissionKey: 'devices.view', active: true },
      { role: 'ADMIN', permissionKey: 'devices.edit', active: true },
      { role: 'ADMIN', permissionKey: 'editions.view', active: true },
      { role: 'ADMIN', permissionKey: 'editions.gest', active: true },
      { role: 'ADMIN', permissionKey: 'editions.edit', active: true },
      { role: 'ADMIN', permissionKey: 'editions.remove', active: true },
      { role: 'ADMIN', permissionKey: 'news_types.view', active: true },
      { role: 'ADMIN', permissionKey: 'news_types.gest', active: true },
      { role: 'ADMIN', permissionKey: 'news_types.edit', active: true },
      { role: 'ADMIN', permissionKey: 'news_types.remove', active: true },
      { role: 'ADMIN', permissionKey: 'permissions.view', active: true },
      { role: 'ADMIN', permissionKey: 'permissions.gest', active: true },
      { role: 'ADMIN', permissionKey: 'permissions.edit', active: true },
      { role: 'ADMIN', permissionKey: 'permissions.remove', active: true },
      { role: 'ADMIN', permissionKey: 'roles.view', active: true },
      { role: 'ADMIN', permissionKey: 'roles.gest', active: true },
      { role: 'ADMIN', permissionKey: 'roles.edit', active: true },
      { role: 'ADMIN', permissionKey: 'roles.remove', active: true },
      { role: 'ADMIN', permissionKey: 'sessions.view', active: true },
      { role: 'ADMIN', permissionKey: 'sessions.edit', active: true },
      { role: 'ADMIN', permissionKey: 'statuses.view', active: true },
      { role: 'ADMIN', permissionKey: 'statuses.gest', active: true },
      { role: 'ADMIN', permissionKey: 'statuses.edit', active: true },
      { role: 'ADMIN', permissionKey: 'statuses.remove', active: true },
      { role: 'ADMIN', permissionKey: 'system.view', active: true },
      { role: 'ADMIN', permissionKey: 'system.gest', active: true },
      { role: 'ADMIN', permissionKey: 'system.edit', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_catalogs.view', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_catalogs.gest', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_catalogs.edit', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_catalogs.remove', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_statuses.view', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_statuses.gest', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_statuses.edit', active: true },
      { role: 'ADMIN', permissionKey: 'ticket_statuses.remove', active: true },
      { role: 'ADMIN', permissionKey: 'emblems.view', active: true },
      { role: 'ADMIN', permissionKey: 'emblems.gest', active: true },
      { role: 'ADMIN', permissionKey: 'emblems.edit', active: true },
      { role: 'ADMIN', permissionKey: 'emblems.give', active: true },
      { role: 'ADMIN', permissionKey: 'emblems.remove', active: true },
      { role: 'ADMIN', permissionKey: 'goals.view', active: true },
      { role: 'ADMIN', permissionKey: 'goals.gest', active: true },
      { role: 'ADMIN', permissionKey: 'goals.edit', active: true },
      { role: 'ADMIN', permissionKey: 'goals.remove', active: true },

      { role: 'MOD', permissionKey: 'menu.start', active: true },
      { role: 'MOD', permissionKey: 'menu.tickets', active: true },
      { role: 'MOD', permissionKey: 'menu.profile', active: true },
      { role: 'MOD', permissionKey: 'menu.players', active: true },
      { role: 'MOD', permissionKey: 'menu.news', active: true },
      { role: 'MOD', permissionKey: 'menu.download', active: true },
      { role: 'MOD', permissionKey: 'menu.configuration', active: true },
      { role: 'MOD', permissionKey: 'menu.aboutapp', active: true },
      { role: 'MOD', permissionKey: 'menu.community', active: true },

      { role: 'POLICE', permissionKey: 'menu.start', active: true },
      { role: 'POLICE', permissionKey: 'menu.tickets', active: true },
      { role: 'POLICE', permissionKey: 'menu.profile', active: true },
      { role: 'POLICE', permissionKey: 'menu.players', active: true },
      { role: 'POLICE', permissionKey: 'menu.news', active: true },
      { role: 'POLICE', permissionKey: 'menu.download', active: true },
      { role: 'POLICE', permissionKey: 'menu.aboutapp', active: true },
      { role: 'POLICE', permissionKey: 'menu.community', active: true },

      { role: 'STREAMER', permissionKey: 'menu.start', active: true },
      { role: 'STREAMER', permissionKey: 'menu.tickets', active: true },
      { role: 'STREAMER', permissionKey: 'menu.profile', active: true },
      { role: 'STREAMER', permissionKey: 'menu.players', active: true },
      { role: 'STREAMER', permissionKey: 'menu.news', active: true },
      { role: 'STREAMER', permissionKey: 'menu.download', active: true },
      { role: 'STREAMER', permissionKey: 'menu.aboutapp', active: true },
      { role: 'STREAMER', permissionKey: 'menu.community', active: true },
      { role: 'STREAMER', permissionKey: 'community.manage', active: true },

      { role: 'USER', permissionKey: 'menu.start', active: true },
      { role: 'USER', permissionKey: 'menu.tickets', active: true },
      { role: 'USER', permissionKey: 'menu.profile', active: true },
      { role: 'USER', permissionKey: 'menu.players', active: true },
      { role: 'USER', permissionKey: 'menu.news', active: true },
      { role: 'USER', permissionKey: 'menu.download', active: true },
      { role: 'USER', permissionKey: 'menu.aboutapp', active: true },
      { role: 'USER', permissionKey: 'menu.community', active: true },
      { role: 'USER', permissionKey: 'menu.configuration', active: true },

      { role: 'VIP', permissionKey: 'menu.start', active: true },
      { role: 'VIP', permissionKey: 'menu.tickets', active: true },
      { role: 'VIP', permissionKey: 'menu.profile', active: true },
      { role: 'VIP', permissionKey: 'menu.players', active: true },
      { role: 'VIP', permissionKey: 'menu.news', active: true },
      { role: 'VIP', permissionKey: 'menu.download', active: true },
      { role: 'VIP', permissionKey: 'menu.aboutapp', active: true },
      { role: 'VIP', permissionKey: 'menu.community', active: true },
      { role: 'VIP', permissionKey: 'menu.configuration', active: true }
    ];

    const existing = await PresetPermissions.findAll({ attributes: ['role', 'permissionKey'] });
    const existingKeys = new Set(existing.map((preset) => `${preset.role}::${preset.permissionKey}`));

    const missingPresetPermissions = seedPresetPermissions.filter(
      (preset) => !existingKeys.has(`${preset.role}::${preset.permissionKey}`)
    );

    if (missingPresetPermissions.length > 0) {
      await PresetPermissions.bulkCreate(missingPresetPermissions);
    }
  };

  return PresetPermissions;
};
